package com.empoderar.picar.model.persistent.caching

object
Constants {
    const val prefEmail = "email"
    const val prefToken = "token"
    const val prefExpiration = "expiration"
    const val prefLogin = "login"
    const val prefPassword = "password"
    const val prefIdUser = "id"
    const val prefUnity = "unity"
    const val prefIsProjectsDownload = "download_projects"
    const val prefIsUnitiesDownload = "download_unities"
    const val prefIsFormsDownload = "download_forms"
    const val prefIsTypesFormsDownload = "download_types_forms"
    const val prefIsContentFormsDownload = "download_content_forms"
    const val preference_picar = "com.empoderar.picar.PREFERENCE_FILE_KEY"
    //const val server = "https://192.168.0.145:44340/api/" //"https://picarservices.azurewebsites.net" //"http://192.168.0.145:44340"
    const val urlBase = "https://192.168.0.9:44340/api/" //"https://picarservices.azurewebsites.net/api/" // //"http://192.168.0.145:1350/api/" //"https://192.168.0.145:44340/api/"
    const val serviceLogin = "Account/Login"
    const val serviceUnit = "Unity"
    const val serviceTypesForm = "Title"
    const val serviceContentForms = "Content"
    const val serviceProjectsByUnit = "Project/GetByUnit/"
    const val serviceProjects = "Project"
    const val serviceFormsByProject = "Form/GetByProject/"
    const val serviceUploadForms = "Form/Insert"
    const val serviceUploadImages = "Photo/Insert"
    const val serviceUploadBodies = "Body/Insert"
    const val seed = "936844983"
}